name: Test

# schedule再登録トリガー用の軽微な更新
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: echo "test"
